ilias:
  image: srsolutions/ilias
  tag: 9-php8.2-apache # or specify a tag
  port: 80
  autoSetup: true
  autoUpdate: 0 # Same as autoSetup if ILIAS >= 7
  devMode: 0
  installArguments: ""
  updateArguments: "" # Same as installArguments if ILIAS >= 7
  skipUpdate: 0 # Only for ILIAS < 6
  db:
    host: "" # Will be set by mariadb chart if left empty
    user: ilias
    password: "" # Overridden by mariadb.auth.rootPassword if not empty
    name: ilias
    dump: setup/sql/ilias3.sql
  clientName: default
  hostName: "" # Defaults to the pod's hostname
  timezone: Europe/Berlin
  maxUploadSize: 200M
  errorsPath: /var/iliasdata/ilias/errors
  memoryLimit: 4096M
  rootPassword: ""
  defaultSkin: default
  defaultStyle: delos
  sessionLifetime: 1800
  dumpAutoload: 0
  phpConfig: |-
    memory_limit = {{ .Values.ilias.memoryLimit }}
    error_reporting = E_ALL & ~E_NOTICE & ~E_WARNING & ~E_STRICT
    log_errors = On
    max_execution_time = 900
    max_input_time = 900
    max_input_vars = 10000
    upload_max_filesize = {{ .Values.ilias.maxUploadSize }}
    post_max_size = {{ .Values.ilias.maxUploadSize }}
    session.gc_maxlifetime = {{ .Values.ilias.sessionLifetime }}
  clientIni: |-
    ; <?php exit; ?>
    [server]
    start = ./login.php

    [client]
    name = {{ .Values.ilias.clientName }}
    description = 
    access = 1

    [db]
    type = innodb
    host = {{ include "ilias.dbHost" . }}
    user = {{ include "ilias.dbUser" . }}
    pass = {{ include "ilias.dbPassword" . }}
    name = {{  include "ilias.dbName" . | quote }}
    port = 3306

    [auth]
    table = usr_data
    usercol = login
    passcol = passwd

    [language]
    default = en
    path = ./lang

    [layout]
    skin = {{ .Values.ilias.defaultSkin }}
    style = {{ .Values.ilias.defaultStyle }}

    [session]
    expire = {{ .Values.ilias.sessionLifetime }}

    [system]
    ROOT_FOLDER_ID = 1
    SYSTEM_FOLDER_ID = 9
    ROLE_FOLDER_ID = 8
    MAIL_SETTINGS_ID = 12
    MAXLENGTH_OBJ_TITLE = 65
    MAXLENGTH_OBJ_DESC = 123
    DEBUG = 0
    DEVMODE = {{ .Values.ilias.devMode }}

    [cache]
    activate_global_cache = 0
    global_cache_service_type = 0
  setupJson: |-
    {
        "common" : {
            "client_id" : "{{ .Values.ilias.clientName }}"
        },
        "database" : {
            "type" : "innodb",
            "host" : "{{ include "ilias.dbHost" . }}",
            "database" : "{{  include "ilias.dbName" . }}",
            "user" : "{{  include "ilias.dbUser" . }}",
            "password" : "{{ include "ilias.dbPassword" . }}",
            "path_to_db_dump" : "setup/sql/ilias3.sql",
            "port" : "3306",
            "create_database": false
        },
        "filesystem" : {
            "data_dir" : "/var/iliasdata/ilias"
        },
        "http" : {
            "path" : "http://{{ .Values.ilias.hostName }}"
        },
        "systemfolder" : {
            "contact" : {
                "firstname" : "Systemadministrator",
                "lastname" : "ILIAS",
                "email" : "noreply@example.com"
            }
        },
        "webservices" : {
            "rpc_server_host" : "{{ .Release.Name }}-ilias-rpc",
            "rpc_server_port" : "{{ .Values.iliasRPCServer.port }}"
        }
    }
  iliasIni: |-
    ; <?php exit; ?>
    [server]
    http_path = http://{{ .Values.ilias.hostName }}
    absolute_path = /var/www/html
    presetting = 
    timezone = {{ .Values.ilias.timezone }}

    [clients]
    path = data
    inifile = client.ini.php
    datadir = /var/iliasdata/ilias
    default = {{ .Values.ilias.clientName }}
    list = 0

    [tools]
    convert = /usr/bin/convert
    zip = /usr/bin/zip
    unzip = /usr/bin/unzip
    java = 
    htmldoc = 
    ffmpeg = /usr/bin/ffmpeg
    ghostscript = /usr/bin/gs
    latex = 
    phantomjs = /usr/local/bin/phantomjs
    vscantype = 
    scancommand = 
    cleancommand = 

    [log]
    ; log to php://stdout (missing slash is added during concat by ilias itself)
    path = php:/
    file = stdout
    enabled = 1
    level = WARNING
    error_path = {{ .Values.ilias.errorsPath }}

    [https]
    auto_https_detect_enabled = 1
    auto_https_detect_header_name = X_FORWARDED_PROTO
    auto_https_detect_header_value = https
  volumes:
    data: # PersistentVolumeClaim configuration for /var/www/html/data
      size: 4Gi
      accessMode: ReadWriteMany
      # storageClass: ""
    iliasdata: # PersistentVolumeClaim configuration for /var/iliasdata/ilias
      size: 4Gi
      accessMode: ReadWriteMany
      # storageClass: ""
  resources:  # Resource requests and limits for the ilias pod.
    requests:
      cpu: 200m
      memory: 4G
    limits:
      cpu: 3
      memory: 6G

iliasRPCServer:
  image: srsolutions/ilias-ilserver
  tag: 9-openjdk17-jre
  nicId: 0
  logLevel: "INFO"
  threads: 1
  ramBufferSize: 256
  maxFileSize: 500
  port: 11111
  iliasIni: |-
    [server]
    absolute_path = /var/www/html/

    [clients]
    inifile = client.ini.php
    path = data
    datadir = iliasdata
  ilServerProperties: |-
    [Server]
    IpAddress = 0.0.0.0
    Port = {{ .Values.iliasRPCServer.port }}
    IndexPath = /var/lucenedata/ilias
    LogFile = /dev/stdout
    LogLevel = {{ .Values.iliasRPCServer.logLevel }}
    NumThreads = {{ .Values.iliasRPCServer.threads }}
    RamBufferSize = {{ .Values.iliasRPCServer.ramBufferSize }}
    IndexMaxFileSizeMB = {{ .Values.iliasRPCServer.maxFileSize }}

    [Client1]
    ClientId = {{ .Values.ilias.clientName }}
    NicId = {{ .Values.iliasRPCServer.nicId }}
    IliasIniPath = /app/ilias.ini.php
  volumes:
    lucene:
      size: 4Gi
      accessMode: ReadWriteOnce
      # storageClass: ""

extraVolumes: []
      # - name: my-volume
      #   mountPath: /path/in/container
      #   readOnly: false # Optional

extraVolumeMounts: []

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx" # Or your ingress controller class
    # Add other annotations as needed
  hosts:
    - host: ilias.example.com # Replace with your domain
      paths:
        - path: /
          pathType: Prefix # Or ImplementationSpecific, Exact
  tls:
    - secretName: ilias-tls # Create this secret with your certificate
      hosts:
        - ilias.example.com # Must match the host above

mariadbGalera:
  enabled: true
  rootUser:
    password: "" # If empty, a password will be generated. Overrides ilias.db.password if set.
  db:
    user: ilias
    password: "" # If empty, a password will be generated. Overrides ilias.db.password if set.
    name: ilias
  persistence:
    enabled: true
    size: 10Gi
  mariadbConfiguration: |-
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    plugin_dir=/opt/bitnami/mariadb/plugin

    [mysqld]
    explicit_defaults_for_timestamp
    default_storage_engine=InnoDB
    basedir=/opt/bitnami/mariadb
    datadir=/bitnami/mariadb/data
    plugin_dir=/opt/bitnami/mariadb/plugin
    tmpdir=/opt/bitnami/mariadb/tmp
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid_file=/opt/bitnami/mariadb/tmp/mysqld.pid
    bind_address=0.0.0.0

    ## Character set
    ##
    init_connect='SET NAMES utf8'

    # ILIAS Options
    join_buffer_size=256M # Increased to 256M (adjust as needed)
    table_open_cache=4096   # Increased to 4096 (adjust as needed)
    innodb_buffer_pool_size=2G # Set to 2G (adjust as needed)
    innodb_large_prefix=OFF # Important for ROW_FORMAT COMPACT
    sql_mode="" # Disables strict mode (important for MySQL 5.7+ and Galera)
    character-set-server=utf8
    collation-server=utf8_general_ci
    max_allowed_packet=32M

    ## MyISAM
    ##
    key_buffer_size=32M
    myisam_recover_options=FORCE,BACKUP

    ## Safety
    ##
    skip_host_cache
    skip_name_resolve
    max_connect_errors=1000000
    sysdate_is_now=1

    ## Binary Logging
    ##
    log_bin=mysql-bin
    expire_logs_days=14
    # Disabling for performance per http://severalnines.com/blog/9-tips-going-production-galera-cluster-mysql
    sync_binlog=0
    # Required for Galera
    binlog_format=row

    ## Caches and Limits
    ##
    tmp_table_size=32M
    max_heap_table_size=32M
    # Re-enabling as now works with Maria 10.1.2
    query_cache_type=1
    query_cache_limit=4M
    query_cache_size=256M
    max_connections=500
    thread_cache_size=50
    open_files_limit=65535
    table_definition_cache=4096

    ## InnoDB
    ##
    innodb=FORCE
    innodb_strict_mode=0
    # Mandatory per https://github.com/codership/documentation/issues/25
    innodb_autoinc_lock_mode=2
    # Per https://www.percona.com/blog/2006/08/04/innodb-double-write/
    innodb_doublewrite=1
    innodb_flush_method=O_DIRECT
    innodb_log_files_in_group=2
    innodb_log_file_size=128M
    innodb_flush_log_at_trx_commit=1
    innodb_file_per_table=1
    # 80% Memory is default reco.
    # Need to re-evaluate when DB size grows
    innodb_file_format=Barracuda

    ## Logging
    ##
    log_error=/opt/bitnami/mariadb/logs/mysqld.log
    slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
    log_queries_not_using_indexes=1
    slow_query_log=1

    ## SSL
    ## Use extraVolumes and extraVolumeMounts to mount /certs filesystem
    # ssl_ca=/certs/ca.pem
    # ssl_cert=/certs/server-cert.pem
    # ssl_key=/certs/server-key.pem

    [galera]
    wsrep_on=ON
    wsrep_provider=/opt/bitnami/mariadb/lib/libgalera_smm.so
    wsrep_sst_method=mariabackup
    wsrep_slave_threads=4
    wsrep_cluster_address=gcomm://
    wsrep_cluster_name=galera
    wsrep_sst_auth="root:"
    # Enabled for performance per https://mariadb.com/kb/en/innodb-system-variables/#innodb_flush_log_at_trx_commit
    innodb_flush_log_at_trx_commit=2
    # MYISAM REPLICATION SUPPORT #
    wsrep_mode=REPLICATE_MYISAM

    [mariadb]
    plugin_load_add=auth_pam

    ## Data-at-Rest Encryption
    ## Use extraVolumes and extraVolumeMounts to mount /encryption filesystem
    # plugin_load_add=file_key_management
    # file_key_management_filename=/encryption/keyfile.enc
    # file_key_management_filekey=FILE:/encryption/keyfile.key
    # file_key_management_encryption_algorithm=AES_CTR
    # encrypt_binlog=ON
    # encrypt_tmp_files=ON

    ## InnoDB/XtraDB Encryption
    # innodb_encrypt_tables=ON
    # innodb_encrypt_temporary_tables=ON
    # innodb_encrypt_log=ON
    # innodb_encryption_threads=4
    # innodb_encryption_rotate_key_age=1

    ## Aria Encryption
    # aria_encrypt_tables=ON
    # encrypt_tmp_disk_tables=ON

mariadb:
  enabled: false
  auth:
    username: ilias
    password: "" 
    rootPassword: "" # If empty, a password will be generated. Overrides ilias.db.password if set.
    database: ilias
  persistence: # Enable persistence for MariaDB data
    enabled: true
    size: 10Gi
  primary: # Add this section for custom my.cnf configuration
    configuration: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      datadir=/bitnami/mariadb/data
      plugin_dir=/opt/bitnami/mariadb/plugin
      port={{ .Values.primary.containerPorts.mysql }}
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      bind-address=*
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      
      slow_query_log=0
      long_query_time=10.0
      binlog_expire_logs_seconds=2592000
      {{- if .Values.tls.enabled }}
      ssl_cert=/opt/bitnami/mariadb/certs/{{ .Values.tls.certFilename }}
      ssl_key=/opt/bitnami/mariadb/certs/{{ .Values.tls.certKeyFilename }}
      {{- if (include "mariadb.tlsCACert" .) }}
      ssl_ca={{ include "mariadb.tlsCACert" . }}
      {{- end }}
      {{- end }}

      # ILIAS Options
      join_buffer_size=256M # Increased to 256M (adjust as needed)
      table_open_cache=500   # Increased to 500 (adjust as needed)
      innodb_buffer_pool_size=2G # Set to 2G (adjust as needed)
      innodb_large_prefix=OFF # Important for ROW_FORMAT COMPACT
      sql_mode="" # Disables strict mode (important for MySQL 5.7+ and Galera)
      character-set-server=UTF8
      collation-server=utf8_general_ci
      max_allowed_packet=32M

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mariadb/plugin

      

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      # other custom my.cnf settings as needed
  # other mariadb values as needed

mariadbBackup:
  enabled: true
  schedule: "0 3 * * *" # 3:00 AM daily
  volume:
    size: 4Gi
    # storageClass: ""

cronjob:
  enabled: true
  image: srsolutions/ilias
  tag: 9-php8.2-apache # or specify a tag
  schedule: "0 2 * * *" # Daily at 2 AM