ilias:
  image: srsolutions/ilias
  tag: 9-php8.2-apache # or specify a tag
  port: 80
  autoSetup: true
  autoUpdate: 0 # Same as autoSetup if ILIAS >= 7
  devMode: 0
  installArguments: ""
  updateArguments: "" # Same as installArguments if ILIAS >= 7
  skipUpdate: 0 # Only for ILIAS < 6
  db:
    host: "" # Will be set by mariadb chart if left empty
    user: ilias
    password: "" # Overridden by mariadb.auth.rootPassword if not empty
    name: ilias
    dump: setup/sql/ilias3.sql
  clientName: default
  hostName: "" # Defaults to the pod's hostname
  timezone: Europe/Berlin
  maxUploadSize: 200M
  errorsPath: /var/iliasdata/ilias/errors
  memoryLimit: 4096M
  rootPassword: ""
  defaultSkin: default
  defaultStyle: delos
  sessionLifetime: 1800
  dumpAutoload: 0
  phpConfig: |-
    memory_limit = {{ .Values.ilias.memoryLimit }}
    error_reporting = E_ALL & ~E_NOTICE & ~E_WARNING & ~E_STRICT
    log_errors = On
    max_execution_time = 900
    max_input_time = 900
    max_input_vars = 10000
    upload_max_filesize = {{ .Values.ilias.maxUploadSize }}
    post_max_size = {{ .Values.ilias.maxUploadSize }}
    session.gc_maxlifetime = {{ .Values.ilias.sessionLifetime }}
  clientIni: |-
    ; <?php exit; ?>
    [server]
    start = ./login.php

    [client]
    name = {{ .Values.ilias.clientName }}
    description = 
    access = 1

    [db]
    type = innodb
    host = {{ include "ilias.dbHost" . }}
    user = {{ .Values.ilias.db.user | default .Values.mariadb.auth.username }}
    pass = {{ .Values.ilias.db.password | default .Values.mariadb.auth.password }}
    name = {{ .Values.ilias.db.name | default .Values.mariadb.auth.database | quote }}
    port = 3306

    [auth]
    table = usr_data
    usercol = login
    passcol = passwd

    [language]
    default = en
    path = ./lang

    [layout]
    skin = {{ .Values.ilias.defaultSkin }}
    style = {{ .Values.ilias.defaultStyle }}

    [session]
    expire = {{ .Values.ilias.sessionLifetime }}

    [system]
    ROOT_FOLDER_ID = 1
    SYSTEM_FOLDER_ID = 9
    ROLE_FOLDER_ID = 8
    MAIL_SETTINGS_ID = 12
    MAXLENGTH_OBJ_TITLE = 65
    MAXLENGTH_OBJ_DESC = 123
    DEBUG = 0
    DEVMODE = {{ .Values.ilias.devMode }}

    [cache]
    activate_global_cache = 0
    global_cache_service_type = 0
  setupJson: |-
    {
        "common" : {
            "client_id" : "{{ .Values.ilias.clientName }}"
        },
        "database" : {
            "type" : "innodb",
            "host" : "{{ include "ilias.dbHost" . }}",
            "database" : "{{ .Values.ilias.db.name | default .Values.mariadb.auth.database | quote }}",
            "user" : "{{ .Values.ilias.db.user | default .Values.mariadb.auth.username }}",
            "password" : "{{ .Values.ilias.db.password | default .Values.mariadb.auth.password }}",
            "path_to_db_dump" : "setup/sql/ilias3.sql",
            "port" : "3306",
            "create_database": false
        },
        "filesystem" : {
            "data_dir" : "/var/iliasdata/ilias"
        },
        "http" : {
            "path" : "http://{{ .Values.ilias.hostName }}"
        },
        "systemfolder" : {
            "contact" : {
                "firstname" : "Systemadministrator",
                "lastname" : "ILIAS",
                "email" : "noreply@example.com"
            }
        },
        "webservices" : {
            "rpc_server_host" : "{{ .Release.Name }}-ilias",
            "rpc_server_port" : "11111"
        }
    }
  iliasIni: |-
    ; <?php exit; ?>
    [server]
    http_path = http://{{ .Values.ilias.hostName }}
    absolute_path = /var/www/html
    presetting = 
    timezone = {{ .Values.ilias.timezone }}

    [clients]
    path = data
    inifile = client.ini.php
    datadir = /var/iliasdata/ilias
    default = {{ .Values.ilias.clientName }}
    list = 0

    [tools]
    convert = /usr/bin/convert
    zip = /usr/bin/zip
    unzip = /usr/bin/unzip
    java = 
    htmldoc = 
    ffmpeg = /usr/bin/ffmpeg
    ghostscript = /usr/bin/gs
    latex = 
    phantomjs = /usr/local/bin/phantomjs
    vscantype = 
    scancommand = 
    cleancommand = 

    [log]
    ; log to php://stdout (missing slash is added during concat by ilias itself)
    path = php:/
    file = stdout
    enabled = 1
    level = WARNING
    error_path = {{ .Values.ilias.errorsPath }}

    [https]
    auto_https_detect_enabled = 1
    auto_https_detect_header_name = X_FORWARDED_PROTO
    auto_https_detect_header_value = https
  volumes:
    data: # PersistentVolumeClaim configuration for /var/www/html/data
      size: 4Gi
      accessMode: ReadWriteMany
      # storageClass: ""
    iliasdata: # PersistentVolumeClaim configuration for /var/iliasdata/ilias
      size: 4Gi
      accessMode: ReadWriteMany
      # storageClass: ""
  resources:  # Resource requests and limits for the ilias pod.
    requests:
      cpu: 200m
      memory: 4G
    limits:
      cpu: 3
      memory: 6G

iliasRPCServer:
  image: srsolutions/ilias-ilserver
  tag: 9-openjdk17-jre
  nicId: 0
  logLevel: "INFO"
  threads: 1
  ramBufferSize: 256
  maxFileSize: 500
  port: 11111
  iliasIni: |-
    [server]
    absolute_path = /app/

    [clients]
    inifile = client.ini.php
    path = data
    datadir = iliasdata
  ilServerProperties: |-
    [Server]
    IpAddress = 0.0.0.0
    Port = {{ .Values.iliasRPCServer.port }}
    IndexPath = /var/lucenedata/ilias
    LogFile = /dev/stdout
    LogLevel = {{ .Values.iliasRPCServer.logLevel }}
    NumThreads = {{ .Values.iliasRPCServer.threads }}
    RamBufferSize = {{ .Values.iliasRPCServer.ramBufferSize }}
    IndexMaxFileSizeMB = {{ .Values.iliasRPCServer.maxFileSize }}

    [Client1]
    ClientId = {{ .Values.ilias.clientName }}
    NicId = {{ .Values.iliasRPCServer.nicId }}
    IliasIniPath = /app/ilias.ini.php
  volumes:
    lucene:
      size: 4Gi
      accessMode: ReadWriteOnce
      # storageClass: ""

extraVolumes: []
      # - name: my-volume
      #   mountPath: /path/in/container
      #   readOnly: false # Optional

extraVolumeMounts: []

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx" # Or your ingress controller class
    # Add other annotations as needed
  hosts:
    - host: ilias.example.com # Replace with your domain
      paths:
        - path: /
          pathType: Prefix # Or ImplementationSpecific, Exact
  tls:
    - secretName: ilias-tls # Create this secret with your certificate
      hosts:
        - ilias.example.com # Must match the host above

mariadb:
  auth:
    username: ilias
    password: "" # If empty, a password will be generated. Overrides ilias.db.password if set.
    rootPassword: "" # If empty, a password will be generated. Overrides ilias.db.password if set.
    database: ilias
  persistence: # Enable persistence for MariaDB data
    enabled: true
    size: 10Gi
  primary: # Add this section for custom my.cnf configuration
    configuration: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      datadir=/bitnami/mariadb/data
      plugin_dir=/opt/bitnami/mariadb/plugin
      port={{ .Values.primary.containerPorts.mysql }}
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      bind-address=*
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      
      slow_query_log=0
      long_query_time=10.0
      binlog_expire_logs_seconds=2592000
      {{- if .Values.tls.enabled }}
      ssl_cert=/opt/bitnami/mariadb/certs/{{ .Values.tls.certFilename }}
      ssl_key=/opt/bitnami/mariadb/certs/{{ .Values.tls.certKeyFilename }}
      {{- if (include "mariadb.tlsCACert" .) }}
      ssl_ca={{ include "mariadb.tlsCACert" . }}
      {{- end }}
      {{- end }}

      # ILIAS Options
      join_buffer_size=256M # Increased to 256M (adjust as needed)
      table_open_cache=500   # Increased to 500 (adjust as needed)
      innodb_buffer_pool_size=2G # Set to 2G (adjust as needed)
      innodb_large_prefix=OFF # Important for ROW_FORMAT COMPACT
      sql_mode="" # Disables strict mode (important for MySQL 5.7+ and Galera)
      character-set-server=UTF8
      collation-server=utf8_general_ci
      max_allowed_packet=32M

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mariadb/plugin

      

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      # other custom my.cnf settings as needed
  # other mariadb values as needed

cronjob:
  enabled: true
  image: srsolutions/ilias
  tag: latest # or specify a tag
  schedule: "0 2 * * *" # Daily at 2 AM