apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name }}-ilias-config
data:
  ilias.ini: |-
    {{- include "common.tplvalues.render" ( dict "value" .Values.ilias.phpConfig "context" $ ) | nindent 4 }}
  ilias-config.php: |-
    {{- include "common.tplvalues.render" ( dict "value" .Values.ilias.iliasIni "context" $ ) | nindent 4 }}
  setup.sh: |-
    mkdir -p /var/www/html/data/{{ .Values.ilias.clientName }} || true
    cp /client.ini.php /var/www/html/data/{{ .Values.ilias.clientName }}/client.ini.php
    chown -R www-data:www-data /var/www/html/data/ 
    chown -R www-data:www-data /var/iliasdata/ilias/ 
    
    mysql="mysql
            --host=${ILIAS_DB_HOST}
            --port=${ILIAS_DB_PORT}
            --user=${ILIAS_DB_USER}
            --password=${ILIAS_DB_PASSWORD}
            ${ILIAS_DB_NAME}"

        # Wait for database
        tries=0
        maxTries=6
        until ${mysql} -e "SELECT VERSION();" &> /dev/null; do
            tries=$((tries + 1))
            if [ $tries -gt $maxTries ]; then
                # give up
                echo "Could not connect to database, aborting"
                exit 1
            fi
            echo "Cannot connect to database, waiting"
            sleep 10
        done
        echo "Database connection established"

        ${mysql} -e "SELECT COUNT(*) FROM settings"

        if [ $? -ne 0 ]; then
            # Run setup
            echo "Running setup"
            su www-data -s /bin/sh -c "php setup/cli.php install -y \
                ${ILIAS_INSTALL_ARGUMENTS} /setup.json"

            # Customize ilias
            echo "Setting root password"
            ${mysql} -e "UPDATE usr_data SET
                    passwd = '$(echo -n ${ILIAS_ROOT_PASSWORD} | md5sum | awk '{print $1}')',
                    passwd_enc_type = 'md5'
                WHERE usr_id = 6"

            echo "Setting skin/style"
            ${mysql} -e "UPDATE usr_pref SET value = '${ILIAS_DEFAULT_SKIN}'
                WHERE keyword = 'skin'"
            ${mysql} -e "UPDATE usr_pref SET value = '${ILIAS_DEFAULT_STYLE}'
                WHERE keyword = 'style'"

            echo "======================================================="
            echo "ILIAS installed successfully!"
            echo "Log in using the following credentials:"
            echo
            echo "User:           root"
            echo "Password:       ${ILIAS_ROOT_PASSWORD}"
            echo "======================================================="
        else
            echo "ILIAS already installed"

            if [ "${ILIAS_AUTO_UPDATE}" -eq "1" ]; then
                echo "Update requested, running setup"
                su www-data -s /bin/sh -c "php setup/cli.php update -y ${ILIAS_UPDATE_ARGUMENTS}"
            fi
        fi
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name }}-ilias-rpc-config
data:
  ilias.ini.php: |-
    {{- include "common.tplvalues.render" ( dict "value" .Values.iliasRPCServer.iliasIni "context" $ ) | nindent 4 }}
  ilServer.properties: |-
    {{- include "common.tplvalues.render" ( dict "value" .Values.iliasRPCServer.ilServerProperties "context" $ ) | nindent 4 }}