apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-ilias-cronjob
  labels:
{{ include "ilias.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ilias-cronjob
              image: {{ .Values.cronjob.image }}:{{ .Values.cronjob.tag }}
              command: ["cron", "-f"]
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                privileged: false
                readOnlyRootFilesystem: true
                runAsGroup: 1001
                runAsNonRoot: true
                runAsUser: 1001
                seLinuxOptions: {}
                seccompProfile:
                  type: RuntimeDefault
              env:
                - name: ILIAS_AUTO_SETUP
                  value: {{ .Values.ilias.autoSetup | quote }}
                - name: ILIAS_AUTO_UPDATE
                  value: {{ .Values.ilias.autoUpdate | quote }}
                - name: ILIAS_DEVMODE
                  value: {{ .Values.ilias.devMode | quote }}
                - name: ILIAS_INSTALL_ARGUMENTS
                  value: {{ .Values.ilias.installArguments | quote }}
                - name: ILIAS_UPDATE_ARGUMENTS
                  value: {{ .Values.ilias.updateArguments | quote }}
                - name: ILIAS_SKIP_UPDATE
                  value: {{ .Values.ilias.skipUpdate | quote }}
                - name: ILIAS_DB_HOST
                  value: {{ include "ilias.dbHost" . | quote }}
                - name: ILIAS_DB_USER
                  value: {{ .Values.ilias.db.user | default .Values.mariadb.auth.username | quote }}
                - name: ILIAS_DB_PASSWORD
                {{- if .Values.ilias.db.password }}
                  value: {{ .Values.ilias.db.password | quote }}
                {{- else }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-mariadb-root-password # From the mariadb chart
                      key: mariadb-root-password
                {{- end }}
                - name: ILIAS_DB_NAME
                  value: {{ .Values.ilias.db.name | quote }}
                - name: ILIAS_DB_DUMP
                  value: {{ .Values.ilias.db.dump | quote }}
                - name: ILIAS_CLIENT_NAME
                  value: {{ .Values.ilias.clientName | quote }}
                - name: ILIAS_HOST_NAME
                  value: {{ .Values.ilias.hostName | quote }}
                - name: ILIAS_TIMEZONE
                  value: {{ .Values.ilias.timezone | quote }}
                - name: ILIAS_MAX_UPLOAD_SIZE
                  value: {{ .Values.ilias.maxUploadSize | quote }}
                - name: ILIAS_ERRORS_PATH
                  value: {{ .Values.ilias.errorsPath | quote }}
                - name: ILIAS_MEMORY_LIMIT
                  value: {{ .Values.ilias.memoryLimit | quote }}
                - name: ILIAS_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-ilias-secrets
                      key: ilias-root-password
                - name: ILIAS_DEFAULT_SKIN
                  value: {{ .Values.ilias.defaultSkin | quote }}
                - name: ILIAS_DEFAULT_STYLE
                  value: {{ .Values.ilias.defaultStyle | quote }}
                - name: ILIAS_INSTALL_CONFIG_PATH
                  value: {{ .Values.ilias.installConfigPath | quote }}
                - name: ILIAS_SESSION_LIFETIME
                  value: {{ .Values.ilias.sessionLifetime | quote }}
                - name: ILIAS_DUMP_AUTOLOAD
                  value: {{ .Values.ilias.dumpAutoload | quote }}
              volumeMounts:
                - name: ilias-data
                  mountPath: /var/www/html/data
                - name: ilias-iliasdata
                  mountPath: /var/iliasdata/ilias
{{- if .Values.extraVolumeMounts }}
{{- toYaml .Values.extraVolumeMounts | nindent 16 }}
{{- end }}
          volumes:
            - name: ilias-data
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-ilias-data
            - name: ilias-iliasdata
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-ilias-iliasdata
{{- if .Values.extraVolumes }}
{{- toYaml .Values.extraVolumes | nindent 12 }}
{{- end }}