apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ilias-ilserver
  labels:
{{ include "ilias.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      ilias/rpc-server: "true"
{{ include "ilias.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        ilias/rpc-server: "true"
{{ include "ilias.labels" . | nindent 8 }}
    spec:
      containers:
        - name: ilias
          image: {{ .Values.ilias.image }}:{{ .Values.ilias.tag }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: {{ .Values.ilias.port }}
          env:
            - name: ILIAS_AUTO_SETUP
              value: {{ .Values.ilias.autoSetup | quote }}
            - name: ILIAS_AUTO_UPDATE
              value: {{ .Values.ilias.autoUpdate | quote }}
            - name: ILIAS_DEVMODE
              value: {{ .Values.ilias.devMode | quote }}
            - name: ILIAS_INSTALL_ARGUMENTS
              value: {{ .Values.ilias.installArguments | quote }}
            - name: ILIAS_UPDATE_ARGUMENTS
              value: {{ .Values.ilias.updateArguments | quote }}
            - name: ILIAS_SKIP_UPDATE
              value: {{ .Values.ilias.skipUpdate | quote }}
            - name: ILIAS_DB_HOST
              value: {{ include "ilias.dbHost" . | quote }}
            - name: ILIAS_DB_USER
              value: {{ .Values.ilias.db.user | default .Values.mariadb.auth.username | quote }}
            - name: ILIAS_DB_PASSWORD
            {{- if .Values.ilias.db.password }}
              value: {{ .Values.ilias.db.password | quote }}
            {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb
                  key: mariadb-password
            {{- end }}
            - name: ILSERVER_LOGLEVEL
              value: {{ .Values.iliasRPCServer.logLevel | quote }}
            - name: ILSERVER_NIC_ID
              value: {{ .Values.iliasRPCServer.nicId | quote }}
            - name: ILSERVER_CLIENT_NAME
              value: {{ .Values.ilias.clientName | quote }}
            - name: ILSERVER_THREADS
              value: {{ .Values.iliasRPCServer.threads | quote }}
            - name: ILSERVER_RAMBUFFER_SIZE
              value: {{ .Values.iliasRPCServer.ramBufferSize | quote }}
            - name: ILSERVER_MAX_FILESIZE
              value: {{ .Values.iliasRPCServer.maxFileSize | quote }}
            - name: ILIAS_ERRORS_PATH
              value: {{ .Values.ilias.errorsPath | quote }}
            - name: ILIAS_MEMORY_LIMIT
              value: {{ .Values.ilias.memoryLimit | quote }}
            - name: ILIAS_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-ilias-secrets
                  key: ilias-root-password
            - name: ILIAS_DEFAULT_SKIN
              value: {{ .Values.ilias.defaultSkin | quote }}
            - name: ILIAS_DEFAULT_STYLE
              value: {{ .Values.ilias.defaultStyle | quote }}
            - name: ILIAS_INSTALL_CONFIG_PATH
              value: {{ .Values.ilias.installConfigPath | quote }}
            - name: ILIAS_SESSION_LIFETIME
              value: {{ .Values.ilias.sessionLifetime | quote }}
            - name: ILIAS_DUMP_AUTOLOAD
              value: {{ .Values.ilias.dumpAutoload | quote }}
          volumeMounts:
            - name: ilias-data
              mountPath: /app/data
            - name: ilias-iliasdata
              mountPath: /app/iliasdata
            - name: ilias-lucence
              mountPath: /var/lucenedata/ilias
{{- if .Values.extraVolumeMounts }}
{{- toYaml .Values.extraVolumeMounts | nindent 12 }}
{{- end }}
          resources: {{ .Values.ilias.resources | toYaml | nindent 12 }}
      volumes:
        - name: ilias-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-ilias-data
        - name: ilias-iliasdata
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-ilias-iliasdata
        - name: ilias-lucence
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-ilias-lucene
{{- if .Values.extraVolumes }}
{{- toYaml .Values.extraVolumes | nindent 8 }}
{{- end }}
