apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name }}-ilias-data
spec:
  accessModes:
    - {{ .Values.ilias.volumes.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.ilias.volumes.data.size }}
  {{- if .Values.ilias.volumes.data.storageClass }}
  storageClassName: {{ .Values.ilias.volumes.data.storageClass }}
  {{- end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name }}-ilias-iliasdata
  labels:
{{ include "ilias.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.ilias.volumes.iliasdata.accessMode }}
  resources:
    requests:
      storage: {{ .Values.ilias.volumes.iliasdata.size }}
  {{- if .Values.ilias.volumes.iliasdata.storageClass }}
  storageClassName: {{ .Values.ilias.volumes.iliasdata.storageClass }}
  {{- end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name }}-ilias-lucene
  labels:
{{ include "ilias.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.iliasRPCServer.volumes.lucene.accessMode }}
  resources:
    requests:
      storage: {{ .Values.iliasRPCServer.volumes.lucene.size | quote }}
  {{- if .Values.iliasRPCServer.volumes.lucene.storageClass }}
  storageClassName: {{ .Values.iliasRPCServer.volumes.lucene.storageClass }}
  {{- end }}
---
{{- if .Values.mariadbBackup.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name }}-mariadb-backup-pvc
spec:
  accessModes: [ "ReadWriteOnce" ] 
  resources:
    requests:
      storage: {{ .Values.mariadbBackup.volume.size | quote }}
  {{- if .Values.mariadbBackup.volume.storageClass }}
  storageClassName: {{ .Values.mariadbBackup.volume.storageClass }}
  {{- end }}
{{- end }}