
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name }}-ilias-secrets
  labels:
{{ include "ilias.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if not .Values.ilias.rootPassword }}
  ilias-root-password: {{ randAlphaNum 32 }}
{{- else }}
  ilias-root-password: {{.Values.ilias.rootPassword }}
{{- end }}
  ilias-client.php: |-
{{- include "common.tplvalues.render" ( dict "value" .Values.ilias.clientIni "context" $ ) | nindent 4 }}
  setup.json: |-
{{- include "common.tplvalues.render" ( dict "value" .Values.ilias.setupJson "context" $ ) | nindent 4 }}