
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name }}-ilias-secrets
  labels:
{{ include "ilias.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if not .Values.ilias.rootPassword }}
  ilias-root-password: {{ randAlphaNum 32 }}
{{- else }}
  ilias-root-password: {{.Values.ilias.rootPassword }}
{{- end }}